{% set name = "sdf" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ScientificDataFormat/SDF-Python/archive/v{{ version }}.tar.gz
  sha256: 469df853021ac2c833948a30e4a8af953988c30ebcdf0a1a74877d9b66b0b909

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - matplotlib-base
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - sdf
    - sdf.examples

about:
  home: https://github.com/ScientificDataFormat/SDF-Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "Work with the Scientific Data Format in Python"

extra:
  recipe-maintainers:
    - t-sommer
